version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      PORT: 8080
      DB_URL: ${DB_URL}
      DB_MIGRATION_URL: ${DB_MIGRATION_URL}
    env_file:
      - .env
